---
APPLY_FIXES: none

BASH_SHELLCHECK_ARGUMENTS:
  - --format
  - gcc

BASH_SHFMT_ARGUMENTS:
  - -i
  - "4"

DISABLE:
  - COPYPASTE
  - SPELL

DISABLE_LINTERS:
  - REPOSITORY_GRYPE

SHOW_ELAPSED_TIME: true

FILEIO_REPORTER: false

PYTHON_DEFAULT_STYLE: ruff

PRINT_ALPACA: false
